name: regression
on:
  [push]   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: 3.9 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
      
      - name: dowload data 
        run: |
          python -c "from download import download_data;  print(download_data())"
      - name: nettoyage de donnee
        run: |
         python -c "from clean_data import missing_values_and_duplicated; print(missing_values_and_duplicated())"
      - name: Removal of unnecessary attributes.
        run: |
         python -c "from remove_attributes import remove_attribut; print(remove_attribut())" 

      - name: Create new attributes.
        run: |
         python -c "from new_attribut import new_tribut; print(new_tribut())" 

      - name: Store the cleaned dataset in an SQLite database.
        run: |
         python -c "from data_connect import connexion; connexion()"  

       - name: Upload Cleaned Data Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Store data 
          path: ./datas.db  
      
    