name: regression
on:
  [push]   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: 3.9 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
      
      - name: dowload data 
        run: |
          python -c "from chargement import download_data; print(download_data())"
          cat data_clean.csv
      - name: nettoyage de donnee
        run: |
         python -c "from clean_data import missing_values_and_duplicated; print(missing_values_and_duplicated())"
         
      
